"""
Few-Shot Learning Prompts for SQL Query Generation
"""

few_shot_prompts = [
    {'Question': "How many Nike t-shirts in XS size and white color?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Brand = 'Nike' AND Size = 'XS' AND Color = 'White';", 'Visualization': 'number'},
    {'Question': "Total value of Puma XXL backpacks?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Brand = 'Puma' AND Category = 'Backpack' AND Size = 'XXL';", 'Visualization': 'number'},
    {'Question': "White Levis blazers for women count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Brand = 'Levis' AND Category = 'Blazer' AND Color = 'White' AND Gender = 'Women';", 'Visualization': 'number'},
    {'Question': "Show top 5 brands by stock", 'SQLQuery': "SELECT Brand, SUM(Stock) as total FROM clothing_data GROUP BY Brand ORDER BY total DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "How many men's shirts total?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Men' AND Category = 'Shirt';", 'Visualization': 'number'},
    {'Question': "Total products in store?", 'SQLQuery': "SELECT COUNT(*) FROM clothing_data;", 'Visualization': 'number'},
    {'Question': "Average price of women's denim blazers?", 'SQLQuery': "SELECT AVG(Price_INR) FROM clothing_data WHERE Category = 'Blazer' AND Material = 'Denim' AND Gender = 'Women';", 'Visualization': 'number'},
    {'Question': "How many unique brands?", 'SQLQuery': "SELECT COUNT(DISTINCT Brand) FROM clothing_data;", 'Visualization': 'number'},
    {'Question': "Unisex woolen products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Wool' AND Gender = 'Unisex';", 'Visualization': 'number'},
    {'Question': "Show top categories by stock", 'SQLQuery': "SELECT Category, SUM(Stock) as total FROM clothing_data GROUP BY Category ORDER BY total DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Total leather products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Leather';", 'Visualization': 'number'},
    {'Question': "Black unisex items?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Unisex' AND Color = 'Black';", 'Visualization': 'number'},
    {'Question': "Most expensive item?", 'SQLQuery': "SELECT Brand, Category, Price_INR FROM clothing_data ORDER BY Price_INR DESC LIMIT 1;", 'Visualization': 'table'},
    {'Question': "Total value of XL shoes?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Size = 'XL' AND Category LIKE '%Shoes%';", 'Visualization': 'number'},
    {'Question': "Green products for women?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Women' AND Color = 'Green';", 'Visualization': 'number'},
    {'Question': "Show stock by gender", 'SQLQuery': "SELECT Gender, SUM(Stock) as total FROM clothing_data GROUP BY Gender;", 'Visualization': 'pie_chart'},
    {'Question': "Categories with XXL?", 'SQLQuery': "SELECT DISTINCT Category FROM clothing_data WHERE Size = 'XXL' ORDER BY Category;", 'Visualization': 'table'},
    {'Question': "Synthetic men's L size?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Synthetic' AND Gender = 'Men' AND Size = 'L';", 'Visualization': 'number'},
    {'Question': "Value of red cotton products?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Material = 'Cotton' AND Color = 'Red';", 'Visualization': 'number'},
    {'Question': "Brands selling women's socks?", 'SQLQuery': "SELECT DISTINCT Brand FROM clothing_data WHERE Category = 'Socks' AND Gender = 'Women';", 'Visualization': 'table'},
    {'Question': "Premium unisex jackets over 5000?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Jacket' AND Gender = 'Unisex' AND Price_INR > 5000;", 'Visualization': 'number'},
    {'Question': "Show Nike size distribution", 'SQLQuery': "SELECT Size, SUM(Stock) as total FROM clothing_data WHERE Brand = 'Nike' GROUP BY Size ORDER BY total DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Denim backpacks?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Backpack' AND Material = 'Denim';", 'Visualization': 'number'},
    {'Question': "Versace total value?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Brand = 'Versace';", 'Visualization': 'number'},
    {'Question': "Material distribution", 'SQLQuery': "SELECT Material, SUM(Stock) as total FROM clothing_data GROUP BY Material;", 'Visualization': 'pie_chart'},
    {'Question': "Compare top 10 brands", 'SQLQuery': "SELECT Brand, SUM(Stock) as total FROM clothing_data GROUP BY Brand ORDER BY total DESC LIMIT 10;", 'Visualization': 'bar_chart'},
    {'Question': "Products per color?", 'SQLQuery': "SELECT Color, SUM(Stock) as total FROM clothing_data GROUP BY Color ORDER BY total DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Price range distribution?", 'SQLQuery': "SELECT CASE WHEN Price_INR < 5000 THEN 'Under 5K' WHEN Price_INR BETWEEN 5000 AND 10000 THEN '5K-10K' ELSE 'Above 10K' END as range, COUNT(*) as count FROM clothing_data GROUP BY range;", 'Visualization': 'bar_chart'},
    {'Question': "Top 5 valuable categories?", 'SQLQuery': "SELECT Category, SUM(Price_INR * Stock) as value FROM clothing_data GROUP BY Category ORDER BY value DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Cotton vs Synthetic?", 'SQLQuery': "SELECT Material, SUM(Stock) as total FROM clothing_data WHERE Material IN ('Cotton', 'Synthetic') GROUP BY Material;", 'Visualization': 'pie_chart'},
    {'Question': "Adidas total value?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Brand = 'Adidas';", 'Visualization': 'number'},
    {'Question': "Nike category count?", 'SQLQuery': "SELECT COUNT(DISTINCT Category) FROM clothing_data WHERE Brand = 'Nike';", 'Visualization': 'number'},
    {'Question': "Total blue products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Color = 'Blue';", 'Visualization': 'number'},
    {'Question': "Brands with joggers?", 'SQLQuery': "SELECT DISTINCT Brand FROM clothing_data WHERE Category = 'Joggers';", 'Visualization': 'table'},
    {'Question': "Average price by category?", 'SQLQuery': "SELECT Category, AVG(Price_INR) as avg FROM clothing_data GROUP BY Category ORDER BY avg DESC LIMIT 10;", 'Visualization': 'bar_chart'},
    {'Question': "Size with least stock?", 'SQLQuery': "SELECT Size, SUM(Stock) as total FROM clothing_data GROUP BY Size ORDER BY total ASC LIMIT 1;", 'Visualization': 'bar_chart'},
    {'Question': "Show all brands", 'SQLQuery': "SELECT DISTINCT Brand FROM clothing_data ORDER BY Brand;", 'Visualization': 'table'},
    {'Question': "Women's products count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Women';", 'Visualization': 'number'},
    {'Question': "Most common color?", 'SQLQuery': "SELECT Color, SUM(Stock) as total FROM clothing_data GROUP BY Color ORDER BY total DESC LIMIT 1;", 'Visualization': 'bar_chart'},
    {'Question': "Zara total inventory?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Brand = 'Zara';", 'Visualization': 'number'},
    {'Question': "Products by price range", 'SQLQuery': "SELECT CASE WHEN Price_INR < 2000 THEN 'Budget' WHEN Price_INR < 10000 THEN 'Mid' ELSE 'Premium' END as segment, COUNT(*) FROM clothing_data GROUP BY segment;", 'Visualization': 'pie_chart'},
    {'Question': "Leather jackets count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Jacket' AND Material = 'Leather';", 'Visualization': 'number'},
    {'Question': "Most expensive brand average?", 'SQLQuery': "SELECT Brand, AVG(Price_INR) as avg FROM clothing_data GROUP BY Brand ORDER BY avg DESC LIMIT 1;", 'Visualization': 'bar_chart'},
    {'Question': "Red products count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Color = 'Red';", 'Visualization': 'number'},
    {'Question': "Show size distribution", 'SQLQuery': "SELECT Size, SUM(Stock) as total FROM clothing_data GROUP BY Size ORDER BY total DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Gucci products?", 'SQLQuery': "SELECT COUNT(*) FROM clothing_data WHERE Brand = 'Gucci';", 'Visualization': 'number'},
    {'Question': "Cheapest item?", 'SQLQuery': "SELECT Brand, Category, Price_INR FROM clothing_data ORDER BY Price_INR ASC LIMIT 1;", 'Visualization': 'table'},
    {'Question': "Total inventory value?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data;", 'Visualization': 'number'},
    {'Question': "XS size products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Size = 'XS';", 'Visualization': 'number'},
    {'Question': "Show brand diversity", 'SQLQuery': "SELECT Brand, COUNT(DISTINCT Color) as colors FROM clothing_data GROUP BY Brand ORDER BY colors DESC LIMIT 5;", 'Visualization': 'bar_chart'}
]
