few_shot_prompts = [
    {'Question': "How many Nike t-shirts in XS size and white color?", 'SQLQuery': "SELECT SUM(Stock) as total_stock FROM clothing_data WHERE Brand = 'Nike' AND Category = 't_shirts' AND Color = 'White' AND Size = 'XS';", 'Visualization': 'number'},
    {'Question': "Total value of Puma XXL backpacks?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) as total_value FROM clothing_data WHERE Brand = 'Puma' AND Category = 'Backpack' AND Size = 'XXL';", 'Visualization': 'number'},
    {'Question': "How many white Levis blazers for women?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Brand = 'Levis' AND Category = 'Blazer' AND Color = 'White' AND Gender = 'Women';", 'Visualization': 'number'},
    {'Question': "Which brand has most green track pants?", 'SQLQuery': "SELECT Brand, SUM(Stock) as stock FROM clothing_data WHERE Category = 'Track Pants' AND Color = 'Green' GROUP BY Brand ORDER BY stock DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "How many men's shirts total?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Shirt' AND Gender = 'Men';", 'Visualization': 'number'},
    {'Question': "Total products in store?", 'SQLQuery': "SELECT COUNT(*) FROM clothing_data;", 'Visualization': 'number'},
    {'Question': "Average price of women's denim blazers?", 'SQLQuery': "SELECT AVG(Price_INR) FROM clothing_data WHERE Category = 'Blazer' AND Material = 'Denim' AND Gender = 'Women';", 'Visualization': 'number'},
    {'Question': "How many unique brands?", 'SQLQuery': "SELECT COUNT(DISTINCT Brand) FROM clothing_data;", 'Visualization': 'number'},
    {'Question': "Unisex woolen products count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Wool' AND Gender = 'Unisex';", 'Visualization': 'number'},
    {'Question': "Category with most red products?", 'SQLQuery': "SELECT Category, SUM(Stock) as stock FROM clothing_data WHERE Color = 'Red' GROUP BY Category ORDER BY stock DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Zara windbreaker sizes available?", 'SQLQuery': "SELECT DISTINCT Size FROM clothing_data WHERE Brand = 'Zara' AND Category = 'Windbreaker' ORDER BY Size;", 'Visualization': 'table'},
    {'Question': "Total leather products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Leather';", 'Visualization': 'number'},
    {'Question': "Black unisex products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Unisex' AND Color = 'Black';", 'Visualization': 'number'},
    {'Question': "Top 5 brands by stock?", 'SQLQuery': "SELECT Brand, SUM(Stock) as stock FROM clothing_data GROUP BY Brand ORDER BY stock DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Most expensive sports bra?", 'SQLQuery': "SELECT Brand, Color, Size, Price_INR FROM clothing_data WHERE Category = 'Sports Bra' ORDER BY Price_INR DESC LIMIT 1;", 'Visualization': 'table'},
    {'Question': "Total value of XL shoes?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Category LIKE '%Shoes%' AND Size = 'XL';", 'Visualization': 'number'},
    {'Question': "Green products for women?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Gender = 'Women' AND Color = 'Green';", 'Visualization': 'number'},
    {'Question': "Brand with cheapest t-shirts?", 'SQLQuery': "SELECT Brand, AVG(Price_INR) as avg FROM clothing_data WHERE Category = 't_shirts' GROUP BY Brand ORDER BY avg ASC LIMIT 1;", 'Visualization': 'bar_chart'},
    {'Question': "Stock by gender pie chart?", 'SQLQuery': "SELECT Gender, SUM(Stock) as stock FROM clothing_data GROUP BY Gender;", 'Visualization': 'pie_chart'},
    {'Question': "Categories with XXL?", 'SQLQuery': "SELECT DISTINCT Category FROM clothing_data WHERE Size = 'XXL' ORDER BY Category;", 'Visualization': 'table'},
    {'Question': "Synthetic men's L size count?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Material = 'Synthetic' AND Gender = 'Men' AND Size = 'L';", 'Visualization': 'number'},
    {'Question': "Value of red cotton products?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Material = 'Cotton' AND Color = 'Red';", 'Visualization': 'number'},
    {'Question': "Brands selling women's socks?", 'SQLQuery': "SELECT DISTINCT Brand FROM clothing_data WHERE Category = 'Socks' AND Gender = 'Women' ORDER BY Brand;", 'Visualization': 'table'},
    {'Question': "Unisex jackets over 5000?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Jacket' AND Gender = 'Unisex' AND Price_INR > 5000;", 'Visualization': 'number'},
    {'Question': "Balenciaga sneaker colors chart?", 'SQLQuery': "SELECT Color, SUM(Stock) as stock FROM clothing_data WHERE Brand = 'Balenciaga' AND Category = 'Sneakers' GROUP BY Color ORDER BY stock DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Louis Vuitton sports bra sizes?", 'SQLQuery': "SELECT DISTINCT Size FROM clothing_data WHERE Brand = 'Louis Vuitton' AND Category = 'Sports Bra';", 'Visualization': 'table'},
    {'Question': "Denim backpacks total?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Category = 'Backpack' AND Material = 'Denim';", 'Visualization': 'number'},
    {'Question': "Versace total value?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Brand = 'Versace';", 'Visualization': 'number'},
    {'Question': "Material distribution pie?", 'SQLQuery': "SELECT Material, SUM(Stock) as stock FROM clothing_data GROUP BY Material;", 'Visualization': 'pie_chart'},
    {'Question': "Size with least stock?", 'SQLQuery': "SELECT Size, SUM(Stock) as stock FROM clothing_data GROUP BY Size ORDER BY stock ASC LIMIT 1;", 'Visualization': 'bar_chart'},
    {'Question': "Compare brands stock chart?", 'SQLQuery': "SELECT Brand, SUM(Stock) as stock FROM clothing_data GROUP BY Brand ORDER BY stock DESC LIMIT 10;", 'Visualization': 'bar_chart'},
    {'Question': "Products per color?", 'SQLQuery': "SELECT Color, SUM(Stock) as stock FROM clothing_data GROUP BY Color ORDER BY stock DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Average stock per brand?", 'SQLQuery': "SELECT Brand, AVG(Stock) as avg FROM clothing_data GROUP BY Brand ORDER BY avg DESC LIMIT 10;", 'Visualization': 'bar_chart'},
    {'Question': "Price range distribution?", 'SQLQuery': "SELECT CASE WHEN Price_INR < 5000 THEN 'Under 5K' WHEN Price_INR BETWEEN 5000 AND 10000 THEN '5K-10K' ELSE 'Above 10K' END as range, COUNT(*) as count FROM clothing_data GROUP BY range;", 'Visualization': 'bar_chart'},
    {'Question': "Top 5 valuable categories?", 'SQLQuery': "SELECT Category, SUM(Price_INR * Stock) as value FROM clothing_data GROUP BY Category ORDER BY value DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Gender stock comparison?", 'SQLQuery': "SELECT Gender, SUM(Stock) as stock FROM clothing_data GROUP BY Gender;", 'Visualization': 'pie_chart'},
    {'Question': "Nike size distribution?", 'SQLQuery': "SELECT Size, SUM(Stock) as stock FROM clothing_data WHERE Brand = 'Nike' GROUP BY Size ORDER BY stock DESC;", 'Visualization': 'bar_chart'},
    {'Question': "Cotton vs Synthetic?", 'SQLQuery': "SELECT Material, SUM(Stock) as stock FROM clothing_data WHERE Material IN ('Cotton', 'Synthetic') GROUP BY Material;", 'Visualization': 'pie_chart'},
    {'Question': "Top 5 expensive products?", 'SQLQuery': "SELECT Brand, Category, Price_INR, Stock FROM clothing_data ORDER BY Price_INR DESC LIMIT 5;", 'Visualization': 'table'},
    {'Question': "Brand with most colors?", 'SQLQuery': "SELECT Brand, COUNT(DISTINCT Color) as colors FROM clothing_data GROUP BY Brand ORDER BY colors DESC LIMIT 5;", 'Visualization': 'bar_chart'},
    {'Question': "Adidas total value?", 'SQLQuery': "SELECT SUM(Price_INR * Stock) FROM clothing_data WHERE Brand = 'Adidas';", 'Visualization': 'number'},
    {'Question': "Nike category count?", 'SQLQuery': "SELECT COUNT(DISTINCT Category) FROM clothing_data WHERE Brand = 'Nike';", 'Visualization': 'number'},
    {'Question': "Puma product types?", 'SQLQuery': "SELECT DISTINCT Category FROM clothing_data WHERE Brand = 'Puma' ORDER BY Category;", 'Visualization': 'table'},
    {'Question': "Total blue products?", 'SQLQuery': "SELECT SUM(Stock) FROM clothing_data WHERE Color = 'Blue';", 'Visualization': 'number'},
    {'Question': "Brands with joggers?", 'SQLQuery': "SELECT DISTINCT Brand FROM clothing_data WHERE Category = 'Joggers' ORDER BY Brand;", 'Visualization': 'table'},
    {'Question': "Average price by category?", 'SQLQuery': "SELECT Category, AVG(Price_INR) as avg FROM clothing_data GROUP BY Category ORDER BY avg
